# раздел содержит информацию относительно настроек биржы
[exchange]
    # имя биржи, записывается в сообщениях, которые отправляет данный шлюз
    name = "kucoin"
    instance = 1

# настройки аккаунта
[account]
    api_key = "61d283fc48decd00016474cc"
    secret_key = "8dcb8034-02b7-4b66-936e-18b473f4e6cb"
    passphrase = "j4J4jdo4dDc"


# от куда получаем информацию о торгуемых монетах
[assets]
    assets = ["BTC", "ETH", "USDT"]

# настройки транспортного уровня
[aeron]
    # Настройки относящиеся к отправке данных
    [aeron.publishers]
        # настройки канала для publishers рассылающего market data
        # ["aeron:udp?control=172.31.14.205:40456|control-mode=dynamic", 111]
        # или
        # ["aeron:ipc", 111]

        [aeron.publishers.orderbook]
            channel = "aeron:udp?control=172.31.14.205:40456|control-mode=dynamic"
            stream_id = 1001
        # настройки publishers осуществляющего отправку баланса
        #        balance = ["aeron:ipc", 111]
        [aeron.publishers.balance]
            channel = "aeron:udp?control=172.31.14.205:40456|control-mode=dynamic"
            stream_id = 1002

        # настройки publishers осуществляющего отправку логов
        # ["channel", channel_id]
        [aeron.publishers.log]
            channel = "aeron:udp?endpoint=3.66.183.27:44444|control-mode=dynamic"
            stream_id = 1001
    # Настройки относящиеся к приему данных.
    [aeron.subscribers]
        # канал в котором приходят команды от ядра.
        #        core = ["aeron:udp?endpoint=54.248.171.18:20121", 555]
        [aeron.subscribers.core]
            channel = "aeron:udp?endpoint=172.31.14.205:40457|control=172.31.14.205:40456"
            stream_id = 1003
